import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/providers";

export const metadata: Metadata = {
  title: "Exam App",
  description: "Generated by seif eldin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-geist`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
